name: CI

on:
  merge_group:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
        toolchain: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Use Rust Cache
        if: ${{ runner.os == 'Linux' }}
        uses: Swatinem/rust-cache@v2.0.1

      - name: Install cargo-generate
        run: cargo install cargo-generate

      - name: Use cargo-generate to generate a new project
        run: cargo generate --path . --name my_project
        